import {useEffect, useState} from "react";
import {ArrowUpRight, ArrowRight, BrainCircuit, Globe2, HeartPulse, Menu, X, Compass, FileCheck2, Workflow, Layers3, ShieldCheck, Users, Building2, Sprout, Stethoscope, Network, Mail, Plus} from "lucide-react";

const capabilities=[
{icon:Compass,title:"See the opportunity",text:"Bring market research, buyer requirements and product context into a clearer view of where to compete.",label:"MARKET INTELLIGENCE"},
{icon:FileCheck2,title:"Understand the requirements",text:"Translate complex trade information into practical preparation steps, with source context and gaps made visible.",label:"TRADE READINESS"},
{icon:Workflow,title:"Move from insight to action",text:"Connect research with the next task: prepare a trade request, organise a document checklist or brief your team.",label:"WORKFLOW ASSISTANCE"},
{icon:Layers3,title:"Intelligence where work happens",text:"Our roadmap brings a shared commerce intelligence layer to DTFS and Sauuki, so insight can travel with the transaction.",label:"CONNECTED COMMERCE"}];
const faqs=[
["What is Nexus Commerce Intelligence?","NCI is our flagship AI initiative for commerce and international trade. It is being developed to help businesses interpret market information, prepare for trade and turn research into practical next steps. It builds on existing foundation models with domain-specific knowledge and workflows."],
["How do NCI, DTFS and NexCare fit together?","Nexus X Industries is the parent company. NCI focuses on commerce intelligence; DTFS organises export readiness and trade execution; NexCare addresses connected digital healthcare. NCI’s planned commerce integrations include DTFS and Sauuki. NexCare is a separate healthcare product—not a trade-AI deployment."],
["Can we explore a pilot or integration?","Yes. We welcome focused discussions with businesses, trade institutions, healthcare organisations and technology partners. Contact us with your use case, intended users and the problem you want to solve. We will discuss current product readiness, pilot scope and implementation requirements."],
["Does NCI replace professional advice?","No. NCI is intended to support research and decisions, not replace customs, legal, financial or other professional advice. Requirements and source data must be checked for the relevant product, destination and date before acting."],
["Where is Nexus X based?","Nexus X Industries is based in Kano, Nigeria, with an ambition to build technology that serves African businesses and communities and connects them to global opportunities."]
];
const contact=(subject:string)=>"mailto:info@nexusind.com?subject="+encodeURIComponent(subject);
function Brand(){return <a href="#top" className="brand supplied-brand" aria-label="Nexus X Industries home"><img src="/nexus-x-logo.png" alt="Nexus X Industries" width={500} height={500}/></a>}
const heroSlides = [
 {name:"NCI",eyebrow:"NEXUS COMMERCE INTELLIGENCE",logo:"/nci-logo.png",lines:["Intelligence for","a world of"],accent:"opportunity.",description:"Meet NCI. Our flagship AI initiative, built to turn the complexity of commerce into clarity—and clarity into action.",cta:"Discover NCI",href:"#nci",secondary:"Explore the Nexus X ecosystem",anchor:"#products",caption:"AFRICAN PERSPECTIVE. GLOBAL POSSIBILITIES."},
 {name:"DTFS",eyebrow:"DIGITAL TRADE FACILITATION SYSTEM",logo:"/dtfs-logo.png",lines:["Local enterprise.","Global markets."],accent:"Connected.",description:"From export readiness to transaction coordination, DTFS helps businesses navigate international trade with greater clarity and confidence.",cta:"Explore DTFS",href:"https://www.dtfsglobal.com",secondary:"Discover our trade platform",anchor:"#dtfs",caption:"OPENING MARKETS. CONNECTING OPPORTUNITY."},
 {name:"NexCare",eyebrow:"CONNECTED HEALTHCARE",logo:"/nexcare-logo.png",lines:["Closer to care.","Wherever"],accent:"life takes you.",description:"Discover NexCare’s vision for connected healthcare—bringing consultations, follow-up and everyday health support into a more continuous care experience.",cta:"Explore NexCare",href:"https://www.nexcareglobal.com",secondary:"Discover connected care",anchor:"#nexcare",caption:"CONNECTED PEOPLE. MORE CONTINUOUS CARE."}
];
function HeroCarousel(){
 const [active,setActive]=useState(0);
 const [paused,setPaused]=useState(false);
 const [reduced,setReduced]=useState(true);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 useEffect(()=>{if(paused||reduced)return;const timer=window.setTimeout(()=>{if(!document.hidden)setActive(current=>(current+1)%heroSlides.length)},5000);return()=>window.clearTimeout(timer)},[active,paused,reduced]);
 useEffect(()=>{const resume=()=>{if(!document.hidden&&!paused&&!reduced)setActive(current=>(current+1)%heroSlides.length)};document.addEventListener('visibilitychange',resume);return()=>document.removeEventListener('visibilitychange',resume)},[paused,reduced]);
 const select=(index:number)=>{setActive((index+heroSlides.length)%heroSlides.length)};
 return <section className="hero hero-carousel" aria-label="Explore Nexus X products" aria-roledescription="carousel">
 <div className="hero-art" aria-hidden="true"/>
 <div className="container hero-content">
 <div className="hero-slides" aria-live={paused||reduced?"polite":"off"}>
 {heroSlides.map((slide,index)=><div key={slide.name} className={`hero-slide ${active===index?'active':''}`} aria-hidden={active!==index} inert={active!==index} role="group" aria-roledescription="slide" aria-label={`${slide.name}, ${index+1} of ${heroSlides.length}`}>
 <p className="eyebrow"><span className="eyebrow-line"/>{slide.eyebrow}</p>
 <div className={`hero-logo-slot logo-${slide.name.toLowerCase()}`}><img src={slide.logo} alt={`${slide.name} logo`}/></div>
 <h1>{slide.lines.map(line=><span className="hero-heading-line" key={line}>{line}</span>)}<span>{slide.accent}</span></h1>
 <p className="hero-description">{slide.description}</p>
 <div className="actions"><a className="button gold" href={slide.href} target={slide.href.startsWith('https')?'_blank':undefined} rel={slide.href.startsWith('https')?'noopener noreferrer':undefined}>{slide.cta}<ArrowUpRight size={19}/></a><a className="text-link" href={slide.anchor}>{slide.secondary}<ArrowRight size={18}/></a></div>
 <p className="hero-caption">{slide.caption}</p>
 </div>)}
 </div>
 <div className="hero-controls" aria-label="Slideshow controls"><button className="hero-arrow" onClick={()=>select(active-1)} aria-label="Previous slide">←</button><div className="hero-selectors">{heroSlides.map((slide,index)=><button key={slide.name} aria-label={`Show ${slide.name} slide`} aria-pressed={active===index} className={active===index?'selected':''} onClick={()=>select(index)}>{slide.name}</button>)}</div><button className="hero-arrow" onClick={()=>select(active+1)} aria-label="Next slide">→</button>{!reduced&&<button className="hero-play" onClick={()=>setPaused(value=>!value)} aria-label={paused?'Start automatic slideshow':'Pause automatic slideshow'}>{paused?'Play':'Pause'}</button>}</div>
 </div><div className="hero-bottom container"><span>A NEXUS X INDUSTRIES INITIATIVE</span></div></section>
}
export default function Home(){const[open,setOpen]=useState(false);
useEffect(()=>{
 if(window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:0.08});
 const targets=document.querySelectorAll('.section > .container, .ecosystem-strip > .container');
 targets.forEach(el=>{el.classList.add('reveal');observer.observe(el)});
 return ()=>{observer.disconnect();targets.forEach(el=>el.classList.remove('reveal'))};
},[]);
return <main id="top">
<a href="#nci" className="skip-link">Skip to content</a>
<header className="header"><div className="container header-inner"><Brand/><nav className={open?"navigation is-open":"navigation"} aria-label="Main navigation">{[["NCI","#nci"],["Our ecosystem","#products"],["Industries","#industries"],["Company","#company"]].map(([t,h])=><a key={t} href={h} onClick={()=>setOpen(false)}>{t}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setOpen(false)}>Connect with us <ArrowUpRight size={16}/></a></nav><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></header>
<HeroCarousel/>
<section id="founder" className="section founder-section" aria-labelledby="founder-heading"><div className="container founder-grid"><figure className="founder-portrait"><img src="/founder-portrait.jpg" alt="Abdullahi Kabir Sani, founder of Nexus X Industries" width={392} height={512} loading="lazy"/><figcaption><span>LEADERSHIP & VISION</span><strong>Abdullahi Kabir Sani</strong><span>Founder, Nexus X Industries</span></figcaption></figure><div className="founder-message"><p className="eyebrow">A MESSAGE FROM OUR FOUNDER</p><h2 id="founder-heading">Building opportunity.<br/><span>Creating lasting value.</span></h2><p className="founder-opening">Our ambition is simple: to build technology that makes opportunity more accessible—and progress more practical.</p><div className="founder-letter"><p>Across Africa, talent and enterprise are everywhere. Yet too many promising ideas encounter the same barriers: fragmented information, complex trade processes and limited access to essential services. At Nexus X Industries, these are the challenges we choose to work on.</p><p>Nexus Commerce Intelligence leads that vision. We are developing NCI to help businesses turn information into understanding, and understanding into informed action. Alongside DTFS, our ambition is to make participation in trade clearer and more accessible. Through NexCare, we are exploring how technology can bring greater continuity and connection to care.</p><p>We believe lasting value comes from disciplined execution: listening to the people we serve, testing our assumptions and earning trust through useful products. Our responsibility is to build with purpose, remain honest about our progress and keep people at the centre of every decision.</p><p>To future partners, customers and collaborators: we invite you to help shape this journey. Together, we can build systems that open doors for businesses and communities, in Africa and beyond.</p></div><div className="founder-signoff"><span className="founder-signature">Abdullahi Kabir Sani</span><span>NEXUS X INDUSTRIES</span></div><a className="text-link" href={contact("Nexus X — Founder’s office enquiry")}>Connect with our team <ArrowUpRight size={18}/></a></div></div></section>
<section className="ecosystem-strip" aria-label="Our areas of focus"><div className="container"><p>One company.<br/><strong>Connected possibilities.</strong></p><a href="#nci"><img className="ecosystem-logo nci-strip-logo" src="/nci-logo.png" alt="" width={709} height={354}/><span>NCI<small>Commerce intelligence</small></span><ArrowUpRight/></a><a href="#dtfs"><Globe2/><span>DTFS<small>Digital trade</small></span><ArrowUpRight/></a><a href="#nexcare"><img className="ecosystem-logo" src="/nexcare-logo.png" alt="" width={1254} height={1254}/><span>NexCare<small>Connected care</small></span><ArrowUpRight/></a></div></section>
<section id="nci" className="section light"><div className="container"><div className="section-heading"><span className="status">IN DEVELOPMENT · PILOT ENQUIRIES WELCOME</span></div><div className="intro-grid"><h2>Commerce is complex.<br/><span>Intelligence changes<br/>what’s possible.</span></h2><div><p className="lead">Nexus Commerce Intelligence is the AI layer we are building for businesses navigating African and global markets.</p><p>Market information is scattered. Requirements are difficult to interpret. Valuable time is lost between knowing what to do and getting it done. NCI brings these challenges into one product vision: contextual intelligence that helps people make informed decisions and take their next step.</p><a className="text-link dark-link" href={contact("NCI — Pilot enquiry")}>Discuss an NCI pilot <ArrowUpRight size={18}/></a></div></div><div className="capabilities">{capabilities.map(c=><article key={c.title}><c.icon size={27}/><small>{c.label}</small><h3>{c.title}</h3><p>{c.text}</p></article>)}</div><p className="disclosure">Capabilities describe our product direction. Availability, data coverage and integrations will be confirmed during pilot scoping.</p></div></section>
<section className="section workflow-section"><div className="container workflow-grid"><div><p className="eyebrow">FROM QUESTION TO NEXT STEP</p><h2>A clearer path<br/>through trade.</h2><p>NCI is designed around the questions real businesses ask. Not another stream of information—a more useful way to work with it.</p><a className="text-link" href={contact("NCI — Product walkthrough request")}>Request a walkthrough <ArrowUpRight size={18}/></a></div><div className="example-panel"><div className="panel-top"><span><BrainCircuit size={20}/> NCI / WORKFLOW CONCEPT</span><span>ILLUSTRATIVE EXAMPLE</span></div><blockquote>“What should I prepare before exporting Nigerian sesame to a new market?”</blockquote><ol><li><span>01</span><div><h3>Clarify the context</h3><p>Product specifications, target destination, buyer expectations and shipment terms.</p></div></li><li><span>02</span><div><h3>Organise the evidence</h3><p>Relevant market information, source references and requirements that need verification.</p></div></li><li><span>03</span><div><h3>Prepare the next action</h3><p>A readiness checklist and a structured brief for the team coordinating the transaction.</p></div></li></ol><div className="panel-note"><ShieldCheck size={18}/> Human judgement stays in control. This is a product concept, not live trade advice.</div></div></div></section>
<section id="products" className="section light"><div className="container"><div className="section-title-row"><h2>Built around the systems<br/>that move people forward.</h2><p>Intelligence leads. Purpose-built platforms turn our ambition into focused solutions for commerce and care.</p></div><div className="product-grid"><article id="dtfs" className="product trade"><div className="product-head"><Globe2 size={31}/><span>TRADE INFRASTRUCTURE</span></div><h3><span className="dtfs-logo-frame"><img src="/dtfs-logo.png" alt="DTFS" width={612} height={408}/></span><span>Digital Trade Facilitation System</span></h3><p>From export readiness to transaction coordination. DTFS is designed to give SMEs, suppliers and buyers a more structured path through international trade.</p><ul><li>Supplier onboarding and business verification workflows</li><li>Trade requests, quotations and digital agreements</li><li>Export-readiness checklists and document coordination</li><li>Buyer–supplier communication and shipment milestones</li></ul><div className="product-foot"><small>FOR EXPORTERS, BUYERS & TRADE PARTNERS</small><a href="https://www.dtfsglobal.com" target="_blank" rel="noreferrer" className="text-link">Explore DTFS <ArrowUpRight size={19}/></a></div></article><article id="nexcare" className="product care"><div className="product-head"><HeartPulse size={31}/><span>HEALTHCARE TECHNOLOGY</span></div><h3><img className="nexcare-product-logo" src="/nexcare-logo.png" alt="NexCare logo" width={1254} height={1254} loading="lazy"/>NexCare<span>Care that stays connected</span></h3><p>Connecting care beyond the consultation. NexCare’s product vision brings patients, clinicians, medication support and health monitoring into a more continuous care experience.</p><ul><li>Remote consultations and patient–clinician communication</li><li>Wearable-enabled vitals monitoring and follow-up</li><li>Medication tracking and pharmacy connections</li><li>Support for chronic-care and underserved communities</li></ul><div className="product-foot"><small>FOR PATIENTS, CLINICIANS & CARE PARTNERS</small><a href="https://www.nexcareglobal.com" target="_blank" rel="noopener noreferrer" className="text-link">Explore NexCare <ArrowUpRight size={19}/></a></div></article></div><div className="commerce-note"><Layers3/><div><strong>A connected commerce roadmap</strong><p>We are developing NCI as a shared intelligence foundation for DTFS and Sauuki, linking market understanding with trade coordination and marketplace workflows.</p></div><a href={contact("NCI — Commerce integration enquiry")}>Discuss integration <ArrowUpRight size={18}/></a></div></div></section>
<section id="industries" className="section industries"><div className="container"><div className="section-title-row"><h2>Real challenges.<br/>Meaningful applications.</h2><p>We begin where better access to information, coordination and services can make a practical difference.</p></div><div className="industry-grid">{[{icon:Sprout,title:"Agriculture & trade",text:"Help producers, cooperatives and exporters organise product information, understand buyer requirements and prepare for market access.",products:"NCI + DTFS"},{icon:Building2,title:"SMEs & commerce",text:"Help growing businesses connect market research with product decisions, transaction preparation and day-to-day commerce.",products:"NCI · COMMERCE ROADMAP"},{icon:Network,title:"Institutions & ecosystems",text:"Explore tools for trade-readiness programmes, business support and structured pilot learning with ecosystem partners.",products:"NCI + DTFS"},{icon:Stethoscope,title:"Health & wellbeing",text:"Explore more accessible follow-up and connected-care workflows with healthcare professionals and service providers.",products:"NEXCARE"}].map(i=><article key={i.title}><i.icon size={25}/><h3>{i.title}</h3><p>{i.text}</p><small>{i.products}</small></article>)}</div></div></section>
<section id="company" className="section company light"><div className="container company-grid"><div><h2>Built in Africa.<br/>Built for what’s next.</h2><p className="lead">Nexus X Industries is an African technology company building digital infrastructure for inclusive growth.</p><p>Our work starts with a simple belief: access to opportunity should not depend on the ability to navigate broken systems. We develop products that connect people to the information, markets and services they need to move forward.</p><p>Based in Kano, Nigeria, we bring a practical understanding of local business realities to a global technology ambition. NCI leads our commerce intelligence strategy, alongside focused platforms in digital trade and connected healthcare.</p><a className="text-link dark-link" href={contact("Nexus X — Company enquiry")}>Get to know Nexus X <ArrowUpRight size={18}/></a></div><aside className="company-statement"><span>OUR NORTH STAR</span><blockquote>Technology should expand who can participate—not just what is possible.</blockquote><div className="statement-rule"/><p>Intelligence. Access. Opportunity.</p><small>NEXUS X INDUSTRIES</small></aside></div></section>
<section id="approach" className="section principles-section"><div className="container"><div className="section-title-row"><h2>Ambitious by design.<br/>Responsible in practice.</h2><p>Our commitments guide product development, pilot design and how we work with partners.</p></div><div className="principle-grid">{[{n:"01",t:"Context before complexity",d:"Start with real users, local constraints and a clearly defined problem. Build only what makes the workflow more useful."},{n:"02",t:"Evidence before claims",d:"Test assumptions through focused pilots. Understand what works, what it costs and what must improve before expanding."},{n:"03",t:"People remain accountable",d:"Design AI to support human judgement. Make uncertainty visible and keep consequential decisions with the right professionals."},{n:"04",t:"Trust is a design requirement",d:"Prioritise appropriate access, careful data handling and transparent product limitations as platforms develop."}].map(p=><article key={p.n}><h3>{p.t}</h3><p>{p.d}</p></article>)}</div></div></section>
<section className="section light faq-section"><div className="container faq-grid"><div><p className="eyebrow">A CLOSER LOOK</p><h2>Your questions.<br/>Clear answers.</h2><p>More about our products, our direction and working with Nexus X.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></div></section>
<section id="contact" className="section contact-section"><div className="container"><p className="eyebrow">LET’S BUILD WHAT’S NEXT</p><h2>The next chapter<br/>starts with <span>a conversation.</span></h2><p>Bring us a problem worth solving, a market worth connecting<br className="desktop-break"/> or a partnership that can create lasting value.</p><div className="contact-options"><a href={contact("NCI — Pilot discussion")}><BrainCircuit/><div><strong>Explore NCI</strong><span>Discuss a use case or pilot.</span></div><ArrowUpRight/></a><a href={contact("Nexus X — Strategic partnership")}><Users/><div><strong>Partner with Nexus X</strong><span>Build an ecosystem together.</span></div><ArrowUpRight/></a><a href={contact("Nexus X — Investor enquiry")}><Building2/><div><strong>Investor conversations</strong><span>Get to know our vision and roadmap.</span></div><ArrowUpRight/></a></div><a className="contact-email" href="mailto:info@nexusind.com">info@nexusind.com <ArrowUpRight size={23}/></a><p className="contact-location">Kano, Nigeria · Technology for inclusive growth</p></div></section>
<footer><div className="container footer-main"><div><Brand/><p>Intelligence that connects.<br/>Technology that opens opportunity.</p></div><div><h3>Our ecosystem</h3><a href="#nci">Nexus Commerce Intelligence</a><a href="#dtfs">DTFS</a><a href="#nexcare">NexCare</a></div><div><h3>Nexus X</h3><a href="#company">Our company</a><a href="#industries">Industries</a><a href="#approach">Our approach</a></div><div><h3>Connect</h3><a href={contact("Nexus X — Partnership enquiry")}>Partnerships</a><a href={contact("Nexus X — Investor enquiry")}>Investor enquiries</a><a href="mailto:info@nexusind.com">General enquiries</a></div></div><div className="container footer-bottom"><span>© 2026 Nexus X Industries Ltd.</span><span>Designed in Nigeria. Built for global opportunity.</span><a href="#top">Back to top ↑</a></div></footer>
</main>}
